### ISSUE TITLE
Still referenced at http://registry.npmjs.org/registry/

### ISSUE THREAD

**Issue by balupton** [DamonOehlman/registry#3]
Is that intentional? http://registry.npmjs.org/ is the official registry of npm right?

**Comment by DamonOehlman** [comment]
Hey Ben - I'm not sure I understand.  I think this package still being visible @ `http://registry.npmjs.org/registry/` makes sense as it's still a published package.  It probably just feels a little weird because of the two registry references :)

Or am I missing something...

**Comment by balupton** [comment]
Ohhhhhhhhhhhh... that's returning this package's data, right... I'm such a couchdb newb.

(trying to figure out how to use the byKeyword view with the nano package - not having much luck)
